service: myfirstproject-lambda
provider:
  name: aws
  runtime: python3.8
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  first-lambda:
    name: first-lambda
    handler: handler.hello
    description: test-lambda
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"

